### ISSUE TITLE
py3 zeronet allows adding % to optional limit and then fails to start silently

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#2097]
### Step 1: Please describe your environment

  * ZeroNet version: py3 4112
  * Operating system: W10
  * Web browser: FF

### Step 2: Describe the problem:

In py3 zeronet modify ZeroHello/Files tab optional limit by adding percentage character. I think you end up with zeronet.conf line:
optional_limit = 20%

quit zeronet, start it again, it does not start. noobie is lost (BAD), experienced user finds log/error.log and inside something like:
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%'.
experienced user is lost (BAD) or he has to google and find this issue where he learn he has to edit zeronet.conf optional_limit line where he remove % and define value in gigabytes, like: "optional_limit = 500" (500 GB space for zeronet data)

Users should not be lost, zeronet should work with % or prevent % be defined by user or report error visible to noobie user so he can research it

**Comment by HelloZeroNet** [comment]
Thanks for reporting it should be fixed by https://github.com/HelloZeroNet/ZeroNet/commit/314c8b22db13e4807cd0f37bb29004b5cd3ecdb4
I have also added a windows message dialog for startup errors: https://github.com/HelloZeroNet/ZeroNet/commit/9526424a47c4383a3f4053e73bf613acedf18446

**Comment by slrslr** [comment]
The issue remains for me, even i updated to latest rev4122 (i have not copied files from github, just did update via zerohello as usual).

```Traceback (most recent call last):
  File "C:\Users\123\Zeronetpy3\core\zeronet.py", line 18, in main
    import main
  File "C:\Users\123\Zeronetpy3\core\src\main.py", line 19, in <module>
    config.parse(silent=True)  # Plugins need to access the configuration
  File "C:\Users\123\Zeronetpy3\core\src\Config.py", line 370, in parse
    argv = self.parseConfig(argv)  # Add arguments from config file
  File "C:\Users\123\Zeronetpy3\core\src\Config.py", line 415, in parseConfig
    for key, val in config.items(section):
  File "configparser.py", line 857, in items
  File "configparser.py", line 857, in <listcomp>
  File "configparser.py", line 854, in <lambda>
  File "configparser.py", line 394, in before_get
  File "configparser.py", line 444, in _interpolate_some
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%'
```

**Comment by HelloZeroNet** [comment]
Yeah sorry, I just pushed the changes to the updater site. It should be Rev4129
