### ISSUE TITLE
Site Manager Save error: No sites found. Already updated.

### ISSUE THREAD

**Issue by vishnuhariam** [HelloZeroNet/ZeroNet#570]
Okay I was just checking the ZeroNet functionality and frankly, I am new to all this. Anyways, I put an index.html file with simple text like "Hello World" to check but, when I sign it, it says, 
SiteManager Save error: No sites found
SiteManager Deleting orphan site from content.db: 16GNrkv7Tf7r6TVUddXXXg7b1qzMdU6pgg

I am using Windows 10. Can anyone help me out?

**Comment by vishnuhariam** [comment]
I also tried with an HTML template, but it still shows me the same error.

**Comment by HelloZeroNet** [comment]
Please try to sign/publish it using the sidebar (drag topright zero button to left)

**Comment by vishnuhariam** [comment]
Thanks a lot for the comment. But,when I drag the sidebar to left, it just keeps loading for a long time. I dunno what I am doing wrong.

**Comment by vishnuhariam** [comment]
Could it be due to the fact that the port 15441 is closed? Am using WiFi from Android.

**Comment by vishnuhariam** [comment]
I have also tried reinstalling from scratch.

**Comment by vishnuhariam** [comment]
Anyways, it started working as soon as I restarted my PC. And, then I signed it but no notification was shown if it was successful or not. Anyways, I went on to publish it, but the publish button on click keeps loading.

**Comment by HelloZeroNet** [comment]
There was an error that affected siteCreate and siteSign command, it should be fixed in the latest Rev1510. Please upgrade (Click on 3dot menu on zerohello > Version 0.4.1...) and try again.

**Comment by vishnuhariam** [comment]
I have already updated to 0.4.1 and I tried again. But, still I get the same error!

**Comment by vishnuhariam** [comment]
OK, so here's what I did.
I skipped signing and set own as true in the sites.json. I then used sitePublish and the site was published and I could access it from another PC with the Zeronet bundle.

**Comment by HelloZeroNet** [comment]
The previous versions has not added the newly created site to sites.json correctly and probably that caused the error, it should work now.

**Comment by vishnuhariam** [comment]
I'd like to tell you that the issue hasn't been fixed. I am still not able to sign the website. The Website Manager still gives me the same error.

**Comment by HelloZeroNet** [comment]
You have to create new site to fix it.

**Comment by vishnuhariam** [comment]
Already tried that multiple times. Tried reinstalling too.

**Comment by HelloZeroNet** [comment]
if you still have the error, then please run it with zeronet.py --debug ... and paste the full log here

**Comment by vishnuhariam** [comment]
Here it is:-
`D:\Softwares\ZeroNet Bundle\ZeroBundle\ZeroNet>"D:\Softwares\ZeroNet Bundle\ZeroBundle\Python\python.exe" zeronet.py --debug siteSign 17RGryGYEe3DS8ZadoPDqvnee7mihjF1cr
- Starting ZeroNet...
PluginManager Loading plugin: AnnounceZero
PluginManager New plugin registered to: Site
PluginManager Loading plugin: CryptMessage
- opensslVerify loaded: <CDLL 'src/lib/opensslVerify/libeay32.dll', handle 11000000 at 3410fd0>
- OpenSSL loaded, version: 01000201F
PluginManager New plugin registered to: UiWebsocket
PluginManager New plugin registered to: User
PluginManager Loading plugin: MergerSite
PluginManager New plugin registered to: UiWebsocket
PluginManager New plugin registered to: UiRequest
PluginManager New plugin registered to: SiteStorage
PluginManager New plugin registered to: Site
PluginManager New plugin registered to: SiteManager
PluginManager Loading plugin: Newsfeed
PluginManager New plugin registered to: UiWebsocket
PluginManager New plugin registered to: User
PluginManager Loading plugin: Sidebar
PluginManager New plugin registered to: UiRequest
PluginManager New plugin registered to: UiWebsocket
PluginManager Loading plugin: Stats
PluginManager New plugin registered to: UiRequest
PluginManager Loading plugin: Trayicon
PluginManager New plugin registered to: Actions
PluginManager Loading plugin: Zeroname
PluginManager New plugin registered to: UiRequest
PluginManager New plugin registered to: ConfigPlugin
PluginManager New plugin registered to: SiteManager
PluginManager New class accepts plugins: ConfigPlugin (Loaded plugins: [<class 'Zeroname.UiRequestPlugin.ConfigPlugin'>, <class 'Config.ConfigPlugin'>])
- Config: Config(action='siteSign', address='17RGryGYEe3DS8ZadoPDqvnee7mihjF1cr', batch=False, bit_resolver='1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F', coffeescript_compiler='type %s | tools\\coffee\\coffee.cmd', config_file='zeronet.conf', connected_limit=10, data_dir='data', debug=True, debug_gevent=False, debug_socket=False, disable_db=False, disable_encryption=False, disable_sslcompression=True, disable_udp=False, fileserver_ip='*', fileserver_port=15441, homepage='1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D', inner_path='content.json', ip_external=None, keep_ssl_cert=False, log_dir='log', max_files_opened=2048, msgpack_purepython=True, open_browser=None, privatekey=None, proxy=None, publish=False, size_limit=10, stream_downloads=False, tor='enable', tor_controller='127.0.0.1:9051', tor_proxy='127.0.0.1:9050', trackers=['zero://boot3rdez4rzn36x.onion:15441', 'zero://boot.zeronet.io#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:15441', 'udp://tracker.coppersurfer.tk:6969', 'udp://tracker.leechers-paradise.org:6969', 'udp://9.rarbg.com:2710', 'http://tracker.aletorrenty.pl:2710/announce', 'http://explodie.org:6969/announce', 'http://torrent.gresille.org/announce'], trackers_file=False, ui_ip='127.0.0.1', ui_port=43110, ui_restrict=False, use_openssl=True, use_tempfiles=False, verbose=False)
PluginManager New class accepts plugins: Actions (Loaded plugins: [<class 'Trayicon.TrayiconPlugin.ActionsPlugin'>, <class 'main.Actions'>])
Db:ContentDb Connected to data/content.db in 0.000s (sqlite version: 2.6.0)...
Db:ContentDb Db version: 4, needed: 4
Db:ContentDb Check tables in 0.157s
PluginManager New class accepts plugins: SiteStorage (Loaded plugins: [<class 'MergerSite.MergerSitePlugin.SiteStoragePlugin'>, <class 'Site.SiteStorage.SiteStorage'>])
PluginManager New class accepts plugins: SiteManager (Loaded plugins: [<class 'Zeroname.SiteManagerPlugin.SiteManagerPlugin'>, <class 'MergerSite.MergerSitePlugin.SiteManagerPlugin'>, <class 'Site.SiteManager.SiteManager'>])
SiteManager SiteManager created.
PluginManager New class accepts plugins: Site (Loaded plugins: [<class 'MergerSite.MergerSitePlugin.SitePlugin'>, <class 'AnnounceZero.AnnounceZeroPlugin.SitePlugin'>, <class 'Site.Site.Site'>])
- Signing site: 17RGryGYEe3DS8ZadoPDqvnee7mihjF1cr...
Site:17RGry..F1cr ContentDb init: 0.015s, found files: 1, sites: 14
PluginManager New class accepts plugins: User (Loaded plugins: [<class 'Newsfeed.NewsfeedPlugin.UserPlugin'>, <class 'CryptMessage.CryptMessagePlugin.UserPlugin'>, <class 'User.User.User'>])
- UserManager added 1 users
User:1GuY2FtyVemtkdwP883RAjRSr3aaRDwiCd Saved in 0.045s
User:1GuY2FtyVemtkdwP883RAjRSr3aaRDwiCd Added new site: 17RGryGYEe3DS8ZadoPDqvnee7mihjF1cr in 0.076s
Private key (input hidden):
Site:17RGry..F1cr Opening site data directory: data/17RGryGYEe3DS8ZadoPDqvnee7mihjF1cr/...
Site:17RGry..F1cr - [SKIPPED] content.json
Site:17RGry..F1cr - index.html (SHA512: c31f0fb7cfd8ce712f44d91c7964aad84d5b22754cdfa3402abb85b3d276e2d8)
Site:17RGry..F1cr Changed files: ['content.json']
Site:17RGry..F1cr Adding timestamp and sha512sums to new content.json...
Site:17RGry..F1cr Verifying private key...
Site:17RGry..F1cr Correct 17RGryGYEe3DS8ZadoPDqvnee7mihjF1cr in valid signers: ['17RGryGYEe3DS8ZadoPDqvnee7mihjF1cr']
Site:17RGry..F1cr Signing content.json...
Site:17RGry..F1cr Saving to content.json...
Site:17RGry..F1cr File content.json signed!
SiteManager Save error: No sites found
SiteManager Sites not loaded yet...
SiteManager Loading sites...
Site:1MaiL5..Ju27 ContentDb init: 0.015s, found files: 9627, sites: 14
SiteManager Loaded site 1MaiL5gfBM1cyb4a8e3iiL8L5gXmoAJu27 in 0.015s
Site:1UDbAD..MkoV ContentDb init: 0.000s, found files: 1230, sites: 14
SiteManager Loaded site 1UDbADib99KE9d3qZ87NqJF2QLTHmMkoV in 0.016s
Site:186THq..z84o ContentDb init: 0.000s, found files: 802, sites: 14
SiteManager Loaded site 186THqMWuptrZxq1rxzpguAivK3Bs6z84o in 0.000s
Site:1MeFqF..q7nH ContentDb init: 0.000s, found files: 1, sites: 14
SiteManager Loaded site 1MeFqFfFFGQfa1J3gJyYYUvb5Lksczq7nH in 0.000s
Site:1Gfey7..fcdp ContentDb init: 0.000s, found files: 1, sites: 14
SiteManager Loaded site 1Gfey7wVXXg1rxk751TBTxLJwhddDNfcdp in 0.000s
Site:17RGry..F1cr ContentDb init: 0.000s, found files: 1, sites: 14
SiteManager Loaded site 17RGryGYEe3DS8ZadoPDqvnee7mihjF1cr in 0.000s
Site:1BLueG..tG49 ContentDb init: 0.000s, found files: 544, sites: 14
SiteManager Loaded site 1BLueGvui1GdbtsjcKqCf4F67uKfritG49 in 0.000s
Site:1BLogC..AGg8 ContentDb init: 0.000s, found files: 413, sites: 14
SiteManager Loaded site 1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8 in 0.000s
Site:1GrEen..yt7i ContentDb init: 0.000s, found files: 608, sites: 14
SiteManager Loaded site 1GrEenUGRWnzaNZjR3XsQa6dQgdPDTyt7i in 0.000s
Site:1Name2..hM9F ContentDb init: 0.000s, found files: 1, sites: 14
SiteManager Loaded site 1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F in 0.015s
Site:1HeLLo..Tf3D ContentDb init: 0.000s, found files: 1, sites: 14
SiteManager Loaded site 1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D in 0.000s
Site:1Gif7P..Xc7h ContentDb init: 0.000s, found files: 1163, sites: 14
SiteManager Loaded site 1Gif7PqWTzVWDQ42Mo7np3zXmGAo3DXc7h in 0.000s
Site:1iD5ZQ..duGz ContentDb init: 0.000s, found files: 1, sites: 14
SiteManager Loaded site 1iD5ZQJMNXu43w1qLB8sfdHVKppVMduGz in 0.000s
Site:1TaLkF..jipT ContentDb init: 0.016s, found files: 3344, sites: 14
SiteManager Loaded site 1TaLkFrMwvbNsooF4ioKAY9EuxTBTjipT in 0.016s
SiteManager SiteManager added 14 sites
SiteManager Updated merger sites in 0.016s
SiteManager Saved sites in 0.22s
SiteManager Updated merger sites in 0.000s`

**Comment by vishnuhariam** [comment]
Here it is, 
`D:\Softwares\ZeroNet Bundle\ZeroBundle\ZeroNet>"D:\Softwares\ZeroNet Bundle\ZeroBundle\Python\python.exe" zeronet.py --debug siteSign 17RGryGYEe3DS8ZadoPDqvnee7mihjF1cr
- Starting ZeroNet...
PluginManager Loading plugin: AnnounceZero
PluginManager New plugin registered to: Site
PluginManager Loading plugin: CryptMessage
- opensslVerify loaded: <CDLL 'src/lib/opensslVerify/libeay32.dll', handle 11000000 at 3410fd0>
- OpenSSL loaded, version: 01000201F
PluginManager New plugin registered to: UiWebsocket
PluginManager New plugin registered to: User
PluginManager Loading plugin: MergerSite
PluginManager New plugin registered to: UiWebsocket
PluginManager New plugin registered to: UiRequest
PluginManager New plugin registered to: SiteStorage
PluginManager New plugin registered to: Site
PluginManager New plugin registered to: SiteManager
PluginManager Loading plugin: Newsfeed
PluginManager New plugin registered to: UiWebsocket
PluginManager New plugin registered to: User
PluginManager Loading plugin: Sidebar
PluginManager New plugin registered to: UiRequest
PluginManager New plugin registered to: UiWebsocket
PluginManager Loading plugin: Stats
PluginManager New plugin registered to: UiRequest
PluginManager Loading plugin: Trayicon
PluginManager New plugin registered to: Actions
PluginManager Loading plugin: Zeroname
PluginManager New plugin registered to: UiRequest
PluginManager New plugin registered to: ConfigPlugin
PluginManager New plugin registered to: SiteManager
PluginManager New class accepts plugins: ConfigPlugin (Loaded plugins: [<class 'Zeroname.UiRequestPlugin.ConfigPlugin'>, <class 'Config.ConfigPlugin'>])
- Config: Config(action='siteSign', address='17RGryGYEe3DS8ZadoPDqvnee7mihjF1cr', batch=False, bit_resolver='1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F', coffeescript_compiler='type %s | tools\\coffee\\coffee.cmd', config_file='zeronet.conf', connected_limit=10, data_dir='data', debug=True, debug_gevent=False, debug_socket=False, disable_db=False, disable_encryption=False, disable_sslcompression=True, disable_udp=False, fileserver_ip='*', fileserver_port=15441, homepage='1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D', inner_path='content.json', ip_external=None, keep_ssl_cert=False, log_dir='log', max_files_opened=2048, msgpack_purepython=True, open_browser=None, privatekey=None, proxy=None, publish=False, size_limit=10, stream_downloads=False, tor='enable', tor_controller='127.0.0.1:9051', tor_proxy='127.0.0.1:9050', trackers=['zero://boot3rdez4rzn36x.onion:15441', 'zero://boot.zeronet.io#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:15441', 'udp://tracker.coppersurfer.tk:6969', 'udp://tracker.leechers-paradise.org:6969', 'udp://9.rarbg.com:2710', 'http://tracker.aletorrenty.pl:2710/announce', 'http://explodie.org:6969/announce', 'http://torrent.gresille.org/announce'], trackers_file=False, ui_ip='127.0.0.1', ui_port=43110, ui_restrict=False, use_openssl=True, use_tempfiles=False, verbose=False)
PluginManager New class accepts plugins: Actions (Loaded plugins: [<class 'Trayicon.TrayiconPlugin.ActionsPlugin'>, <class 'main.Actions'>])
Db:ContentDb Connected to data/content.db in 0.000s (sqlite version: 2.6.0)...
Db:ContentDb Db version: 4, needed: 4
Db:ContentDb Check tables in 0.157s
PluginManager New class accepts plugins: SiteStorage (Loaded plugins: [<class 'MergerSite.MergerSitePlugin.SiteStoragePlugin'>, <class 'Site.SiteStorage.SiteStorage'>])
PluginManager New class accepts plugins: SiteManager (Loaded plugins: [<class 'Zeroname.SiteManagerPlugin.SiteManagerPlugin'>, <class 'MergerSite.MergerSitePlugin.SiteManagerPlugin'>, <class 'Site.SiteManager.SiteManager'>])
SiteManager SiteManager created.
PluginManager New class accepts plugins: Site (Loaded plugins: [<class 'MergerSite.MergerSitePlugin.SitePlugin'>, <class 'AnnounceZero.AnnounceZeroPlugin.SitePlugin'>, <class 'Site.Site.Site'>])
- Signing site: 17RGryGYEe3DS8ZadoPDqvnee7mihjF1cr...
Site:17RGry..F1cr ContentDb init: 0.015s, found files: 1, sites: 14
PluginManager New class accepts plugins: User (Loaded plugins: [<class 'Newsfeed.NewsfeedPlugin.UserPlugin'>, <class 'CryptMessage.CryptMessagePlugin.UserPlugin'>, <class 'User.User.User'>])
- UserManager added 1 users
User:1GuY2FtyVemtkdwP883RAjRSr3aaRDwiCd Saved in 0.045s
User:1GuY2FtyVemtkdwP883RAjRSr3aaRDwiCd Added new site: 17RGryGYEe3DS8ZadoPDqvnee7mihjF1cr in 0.076s
Private key (input hidden):
Site:17RGry..F1cr Opening site data directory: data/17RGryGYEe3DS8ZadoPDqvnee7mihjF1cr/...
Site:17RGry..F1cr - [SKIPPED] content.json
Site:17RGry..F1cr - index.html (SHA512: c31f0fb7cfd8ce712f44d91c7964aad84d5b22754cdfa3402abb85b3d276e2d8)
Site:17RGry..F1cr Changed files: ['content.json']
Site:17RGry..F1cr Adding timestamp and sha512sums to new content.json...
Site:17RGry..F1cr Verifying private key...
Site:17RGry..F1cr Correct 17RGryGYEe3DS8ZadoPDqvnee7mihjF1cr in valid signers: ['17RGryGYEe3DS8ZadoPDqvnee7mihjF1cr']
Site:17RGry..F1cr Signing content.json...
Site:17RGry..F1cr Saving to content.json...
Site:17RGry..F1cr File content.json signed!
SiteManager Save error: No sites found
SiteManager Sites not loaded yet...
SiteManager Loading sites...
Site:1MaiL5..Ju27 ContentDb init: 0.015s, found files: 9627, sites: 14
SiteManager Loaded site 1MaiL5gfBM1cyb4a8e3iiL8L5gXmoAJu27 in 0.015s
Site:1UDbAD..MkoV ContentDb init: 0.000s, found files: 1230, sites: 14
SiteManager Loaded site 1UDbADib99KE9d3qZ87NqJF2QLTHmMkoV in 0.016s
Site:186THq..z84o ContentDb init: 0.000s, found files: 802, sites: 14
SiteManager Loaded site 186THqMWuptrZxq1rxzpguAivK3Bs6z84o in 0.000s
Site:1MeFqF..q7nH ContentDb init: 0.000s, found files: 1, sites: 14
SiteManager Loaded site 1MeFqFfFFGQfa1J3gJyYYUvb5Lksczq7nH in 0.000s
Site:1Gfey7..fcdp ContentDb init: 0.000s, found files: 1, sites: 14
SiteManager Loaded site 1Gfey7wVXXg1rxk751TBTxLJwhddDNfcdp in 0.000s
Site:17RGry..F1cr ContentDb init: 0.000s, found files: 1, sites: 14
SiteManager Loaded site 17RGryGYEe3DS8ZadoPDqvnee7mihjF1cr in 0.000s
Site:1BLueG..tG49 ContentDb init: 0.000s, found files: 544, sites: 14
SiteManager Loaded site 1BLueGvui1GdbtsjcKqCf4F67uKfritG49 in 0.000s
Site:1BLogC..AGg8 ContentDb init: 0.000s, found files: 413, sites: 14
SiteManager Loaded site 1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8 in 0.000s
Site:1GrEen..yt7i ContentDb init: 0.000s, found files: 608, sites: 14
SiteManager Loaded site 1GrEenUGRWnzaNZjR3XsQa6dQgdPDTyt7i in 0.000s
Site:1Name2..hM9F ContentDb init: 0.000s, found files: 1, sites: 14
SiteManager Loaded site 1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F in 0.015s
Site:1HeLLo..Tf3D ContentDb init: 0.000s, found files: 1, sites: 14
SiteManager Loaded site 1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D in 0.000s
Site:1Gif7P..Xc7h ContentDb init: 0.000s, found files: 1163, sites: 14
SiteManager Loaded site 1Gif7PqWTzVWDQ42Mo7np3zXmGAo3DXc7h in 0.000s
Site:1iD5ZQ..duGz ContentDb init: 0.000s, found files: 1, sites: 14
SiteManager Loaded site 1iD5ZQJMNXu43w1qLB8sfdHVKppVMduGz in 0.000s
Site:1TaLkF..jipT ContentDb init: 0.016s, found files: 3344, sites: 14
SiteManager Loaded site 1TaLkFrMwvbNsooF4ioKAY9EuxTBTjipT in 0.016s
SiteManager SiteManager added 14 sites
SiteManager Updated merger sites in 0.016s
SiteManager Saved sites in 0.22s
SiteManager Updated merger sites in 0.000s`

**Comment by vishnuhariam** [comment]
[log.txt](https://github.com/HelloZeroNet/ZeroNet/files/458164/log.txt)

I have also attached the log as txt.

**Comment by HelloZeroNet** [comment]
This looks normal, whats the exact problem?

**Comment by vishnuhariam** [comment]
The problem is the same as said in the title. Okay, let me explain. 
The siteCreate command does its job well, But, each time I run siteSign, it gives me the following error: "SiteManager Save error: No sites found"
And, even if I publish it, it won't work properly because once I use the sidebar to edit the Title and Description, it doesn't change at all. Moreover, I have tried to use the sidebar to Sign and Publish, but after clicking Sign and providing the Private key, there's nothing being shown, no notification saying it's done.
If I somehow disregard the siteSign problem and directly Publish, everytime the site says, "One file update failed" and I can't edit any information using the sidebar.

**Comment by HelloZeroNet** [comment]
You can ignore the "SiteManager Save error: No sites found" error.

I have just tried and works for me:
 - Stopped ZeroNet
 - zeronet.py siteCreate
 - Started ZeroNet
 - Clicked the new site's link on ZeroHello
 - Modified the title
 - Signed it
 - Loaded the site on a remote machine
 - Modified the .html file
 - Signed/Published it

**Comment by vishnuhariam** [comment]
Let me check and I'll let you know.

**Comment by vishnuhariam** [comment]
Thanks a lot, Owner. Really starting to love it. And, once again, thanks for the quick replies. All the best and regards.
